name: QA DevOps Automation CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run API tests with Newman
        run: npm run api-test

      - name: Run UI tests with Cypress
        run: |
          npx cypress run --config-file ui-tests/cypress.config.js

      - name: Generate UI report (Mochawesome)
        run: |
          npx mochawesome-merge ui-tests/cypress/reports/.jsons/*.json | npx mochawesome-report-generator --reportDir ui-tests/cypress/reports --reportFilename index.html

      - name: Upload UI report
        uses: actions/upload-artifact@v4
        with:
          name: ui-report
          path: ui-tests/cypress/reports/index.html
      - name: Check if mochawesome reports exist
  run: |
    if ls ui-tests/cypress/reports/.jsons/*.json 1> /dev/null 2>&1; then
      npx mochawesome-merge ui-tests/cypress/reports/.jsons/*.json | npx mochawesome-report-generator --reportDir ui-tests/cypress/reports --reportFilename index.html
    else
      echo "⚠️ No JSON reports found. Skipping report generation."
    fi

