name: QA DevOps Automation CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run API tests with Newman
        run: npm run api-test

      - name: Run UI tests with Cypress
        run: |
          npx cypress run --config-file ui-tests/cypress.config.js

      - name: Generate UI report (Mochawesome)
        run: |
          json_files=$(find ui-tests/cypress/reports/.jsons -name "*.json" -print0 | xargs -0)
          if [ -n "$json_files" ]; then
            echo "✅ JSON files found, generating report..."
            echo "Files: $json_files"
            npx mochawesome-merge $json_files | npx mochawesome-report-generator --reportDir ui-tests/cypress/reports --reportFilename index.html
          else
            echo "⚠️ No mochawesome JSON files found. Skipping report generation."
          fi

      - name: Upload UI report
        uses: actions/upload-artifact@v4
        with:
          name: ui-report
          path: ui-tests/cypress/reports
